### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by Oliversw** [fac-15/snowflakes#29]
Relates #96

- [x] Create page and ensure that it is connected to a route
- [x] Add content
- [x] Basic styling
- [x] Ensure that button is connect to Top Three page

After review:
- [x] Bring style in line with @teenie-quaggard's new design
- [x] Include small instructions section
- [x] Soft scroll to instructions section
- [x] Fade title in on page load

First Figma:
![screen shot 2019-01-15 at 12 15 38 pm](https://user-images.githubusercontent.com/9094166/51180111-55dedd80-18bf-11e9-9963-3a4dcbbeba88.png)

Figma after redesign:
![screen shot 2019-01-21 at 11 51 46 am](https://user-images.githubusercontent.com/9094166/51472988-fd9e5480-1d72-11e9-9655-5c8f7a376087.png)

**Comment by Cleop** [comment]
@oliversw - do you have a desktop design screenshot you can share here for this page?
                  - what endpoint should the 'Let's Go' link take you to?
                  - do you have an asset for the arrow under the link? If so, where can the team get hold of it? Can you paste it in here for easy access?

**Comment by Cleop** [comment]
@Oliversw - don't forget to remove the `in-progress` label on this one 😉

**Comment by Oliversw** [comment]
Thanks for that @Cleop!
