### ISSUE TITLE
Look into animation for displaying goal/ethos/instruction text

### ISSUE THREAD

**Issue by Oliversw** [fac-15/snowflakes#47]
relates #10

- [ ] Research examples
- [ ] Implement on page

(Add to this as necessary please! :))

**Comment by Cleop** [comment]
@Oliversw - you may want to think about non js options for this e.g. css only implementations for hiding/showing text

Also, remember people have a short attention span. Are you adding more text for the sake of the page being able to have animations or could you reduce the text and therefore not need these? A better website is one that the user can easily find there way around and get what they want from. So always ask yourself do I _need_ this or is there a simpler, more user friendly way I could achieve the same thing?

**Comment by Oliversw** [comment]
Redesigned pages so this should no longer be too necessary
